from _model.shared import *
from _model.user import *
from _model.uc import *
from _model.language import *
from _model.teacher import *
from _model.course_type import *
from _model.academic import *
from _model.affiliation import *
from _model.publication import *
from _model.uc_teacher import *
from _model.laboratory import *